<?php

/**
 * Class defines all details about the AI Visibility tool - Phase 1
 * (AI referral tracking via a JS snippet). Setup screen, report screen,
 * and the public beacon ingest handler (called only from
 * aivisibility-collect.php, never from the authenticated dispatch tree).
 */
class AIVisibilityController extends Controller {

	// Managed-block markers for robots.txt writes (see __writeRobotsTxt()) -
	// only content between these two lines is ever touched; everything else
	// in the site's robots.txt survives untouched.
	const ROBOTS_BLOCK_BEGIN = '# BEGIN SEO PANEL AI RULES';
	const ROBOTS_BLOCK_END = '# END SEO PANEL AI RULES';

	// Managed-block markers for .htaccess writes (see __writeHtaccessRules()) -
	// same containment guarantee as the robots.txt markers above.
	const HTACCESS_BLOCK_BEGIN = '# BEGIN SEO PANEL AI HEADERS';
	const HTACCESS_BLOCK_END = '# END SEO PANEL AI HEADERS';

	// Marker comment prefixed onto every llms.txt SEO Panel generates -
	// distinguishes "safe to regenerate" from a hand-authored file that
	// happens to already exist (see regenerateLlmsTxt()).
	const LLMS_TXT_MARKER = '<!-- Generated by SEO Panel -->';

	// Traffic anomaly alerts (see checkTrafficAnomalies()): a week-over-week
	// swing below this percentage is treated as normal noise, and a prior
	// week total below this floor is ignored entirely (a jump from 2 hits
	// to 6 is a 200% swing but not a meaningful signal).
	const ANOMALY_THRESHOLD_PCT = 50;
	const ANOMALY_MIN_BASELINE = 10;

	# func to show the setup screen (site picker + snippet + install status)
	function showSetup($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$this->set('websiteList', $websiteList);

		if (empty($websiteList)) {
			$this->set('spTextWebsite', $this->getLanguageTexts('website', $_SESSION['lang_code']));
			$this->render('dashboard/no_websites');
			return;
		}

		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		$this->set('websiteId', $websiteId);

		$siteInfo = $this->__getOrCreateSite($websiteId, $websiteList);
		$this->set('siteInfo', $siteInfo);
		$this->set('snippetUrl', SP_WEBPATH . "/aivisibility.js.php");
		$this->set('botCollectorUrl', SP_WEBPATH . "/aibot-collector.php?website_id=" . intval($websiteId));

		// on-premise server access: local docroot (robots.txt/llms.txt) +
		// access log path (Feature B), admin-configured, see
		// __validateDocrootPath()/__validateAccessLogPath()
		$accessInfo = $this->__getSiteAccessConfig($websiteId);
		$this->set('accessInfo', $accessInfo);

		$docrootStatus = !empty($accessInfo['docroot_path']) ? $this->__validateDocrootPath($accessInfo['docroot_path']) : null;
		$this->set('docrootStatus', $docrootStatus);

		$accessLogStatus = !empty($accessInfo['access_log_path']) ? $this->__validateAccessLogPath($accessInfo['access_log_path']) : null;
		$this->set('accessLogStatus', $accessLogStatus);

		// zero-touch WordPress install: only offered when the admin has
		// configured a writable docroot AND WordPress is actually detected there
		$this->set('wpDetected', !empty($docrootStatus['writable']) && $this->__detectWordPress($docrootStatus['real']));
		$this->set('wpCollectorInstalled', !empty($docrootStatus['real']) && $this->__isWpCollectorInstalled($docrootStatus['real']));

		// AI-bot response headers (v1: X-Robots-Tag via managed .htaccess block)
		$this->set('htaccessExtensions', !empty($accessInfo['htaccess_extensions']) ? explode(',', $accessInfo['htaccess_extensions']) : []);
		$this->set('htaccessEnabled', !empty($accessInfo['htaccess_ai_headers_enabled']));
		$this->set('htaccessLastWrittenAt', $accessInfo['htaccess_last_written_at'] ?? null);
		$this->set('htaccessLastError', $accessInfo['htaccess_last_error'] ?? null);

		$websiteInfo = null;
		foreach ($websiteList as $w) {
			if ($w['id'] == $websiteId) { $websiteInfo = $w; break; }
		}
		$this->set('websiteInfo', $websiteInfo);
		$this->set('robotsPreview', !empty($websiteInfo['url']) ? $this->__fetchRobotsTxtPreview($websiteInfo['url']) : null);

		// GROUP BY platform: a platform (e.g. chatgpt) can have multiple
		// ai_platforms rows (chatgpt.com, chat.openai.com) - one toggle row
		// per platform. MIN() since display_name/bot_ua_pattern are the same
		// across a platform's rows in practice, but ONLY_FULL_GROUP_BY still
		// requires every non-grouped column to be wrapped in an aggregate.
		$robotsPlatformList = $this->db->select("SELECT platform, MIN(display_name) AS display_name, MIN(bot_ua_pattern) AS bot_ua_pattern FROM ai_platforms WHERE is_active=1 AND bot_ua_pattern IS NOT NULL AND bot_ua_pattern != '' GROUP BY platform ORDER BY display_name");
		$this->set('robotsPlatformList', $robotsPlatformList);

		$ruleRows = $this->db->select("SELECT platform, is_blocked FROM ai_visibility_robots_rules WHERE website_id=" . intval($websiteId));
		$this->set('robotsRuleMap', array_column($ruleRows, 'is_blocked', 'platform'));

		include_once(SP_CTRLPATH . "/settings.ctrl.php");
		$this->set('localAiAvailable', SettingsController::isLocalAIEnabled());

		$this->render('aivisibility/setup');
	}

	/**
	 * "AI Visibility at a glance" dashboard: combines the 30-day totals from
	 * the 3 otherwise-siloed reports (AI Referrals, AI Bot Crawlers, AI
	 * Overview) into one screen, plus a merged per-platform breakdown - no
	 * new data collection, purely new aggregate queries over tables each
	 * full report already reads (ai_referrals, ai_bot_hits, searchresults).
	 */
	function showOverview($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$this->set('websiteList', $websiteList);

		if (empty($websiteList)) {
			$this->set('spTextWebsite', $this->getLanguageTexts('website', $_SESSION['lang_code']));
			$this->render('dashboard/no_websites');
			return;
		}

		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		$this->set('websiteId', $websiteId);

		// date range: matches the AI Referral/AI Bot Crawler reports'
		// from_time/to_time pattern - AI Overview citation rate below is
		// deliberately NOT range-filtered (it's each keyword's LATEST
		// measured state, not a time series, same as aioverview.ctp.php's
		// own report has no date range either)
		$fromTime = !empty($info['from_time']) ? $info['from_time'] : date('Y-m-d', strtotime('-30 days'));
		$toTime = !empty($info['to_time']) ? $info['to_time'] : date('Y-m-d');
		$this->set('fromTime', $fromTime);
		$this->set('toTime', $toTime);

		$fromTimeSql = addslashes($fromTime);
		$toTimeSql = addslashes($toTime);

		$referralTotal = intval($this->db->select("SELECT COALESCE(SUM(hits),0) AS total FROM ai_referrals WHERE website_id=$websiteId AND hit_date >= '$fromTimeSql' AND hit_date <= '$toTimeSql'", true)['total']);
		$botTotal = intval($this->db->select("SELECT COALESCE(SUM(hits),0) AS total FROM ai_bot_hits WHERE website_id=$websiteId AND hit_date >= '$fromTimeSql' AND hit_date <= '$toTimeSql'", true)['total']);
		$this->set('referralTotal', $referralTotal);
		$this->set('botTotal', $botTotal);

		// merge referral + bot totals per platform for one combined table,
		// rather than making the user cross-reference two separate reports
		$this->set('combinedPlatforms', $this->__getCombinedPlatformTotals($websiteId, $fromTimeSql, $toTimeSql));

		$this->set('aioSummary', $this->__getAioSummaryForWebsite($websiteId));

		$this->render('aivisibility/overview');
	}

	// func to merge ai_referrals + ai_bot_hits totals per platform for one
	// date range - shared by showOverview()'s on-screen table and
	// exportOverviewCsv(), so the export always matches what's on screen.
	// $fromTimeSql/$toTimeSql must already be addslashes()-escaped.
	function __getCombinedPlatformTotals($websiteId, $fromTimeSql, $toTimeSql) {
		$websiteId = intval($websiteId);
		$referralByPlatform = $this->db->select("SELECT platform, SUM(hits) AS hits FROM ai_referrals WHERE website_id=$websiteId AND hit_date >= '$fromTimeSql' AND hit_date <= '$toTimeSql' GROUP BY platform");
		$botByPlatform = $this->db->select("SELECT platform, SUM(hits) AS hits FROM ai_bot_hits WHERE website_id=$websiteId AND hit_date >= '$fromTimeSql' AND hit_date <= '$toTimeSql' GROUP BY platform");

		$platformDisplayNames = array_column($this->db->select("SELECT platform, MIN(display_name) AS display_name FROM ai_platforms GROUP BY platform"), 'display_name', 'platform');

		$combined = [];
		foreach ($referralByPlatform as $row) {
			$combined[$row['platform']]['referrals'] = intval($row['hits']);
		}
		foreach ($botByPlatform as $row) {
			$combined[$row['platform']]['bot_hits'] = intval($row['hits']);
		}
		foreach ($combined as $platform => &$row) {
			$row['platform'] = $platform;
			$row['display_name'] = $platformDisplayNames[$platform] ?? $platform;
			$row['referrals'] = $row['referrals'] ?? 0;
			$row['bot_hits'] = $row['bot_hits'] ?? 0;
			$row['total'] = $row['referrals'] + $row['bot_hits'];
		}
		unset($row);
		uasort($combined, function($a, $b) { return $b['total'] - $a['total']; });
		return $combined;
	}

	# func to export the Overview dashboard's combined per-platform table (same range as showOverview()) as CSV
	function exportOverviewCsv($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		if (empty($websiteId)) {
			exit;
		}

		$fromTime = !empty($info['from_time']) ? $info['from_time'] : date('Y-m-d', strtotime('-30 days'));
		$toTime = !empty($info['to_time']) ? $info['to_time'] : date('Y-m-d');

		$combined = $this->__getCombinedPlatformTotals($websiteId, addslashes($fromTime), addslashes($toTime));
		$this->__streamCsv("ai-visibility-overview-$websiteId-$fromTime-to-$toTime.csv", ['Platform', 'Referrals', 'Bot Crawls', 'Total'], $combined, ['display_name', 'referrals', 'bot_hits', 'total']);
	}

	/**
	 * Admin-only: configure a website's local server access (docroot for
	 * robots.txt/llms.txt, access log path for Feature B's bot detection).
	 * This is the trust boundary - granting either path means SEO Panel
	 * gets real filesystem read/write with the web server's own OS
	 * permissions, and SEO Panel is multi-tenant (many non-admin users each
	 * manage their own websites), so only an admin may set these. Once set,
	 * the website's own owner can self-serve the day-to-day robots.txt
	 * toggles/llms.txt regeneration via toggleRobotsRule()/regenerateLlmsTxt()
	 * below without further admin involvement.
	 *
	 * Deliberately does not hard-reject a currently-invalid/non-writable
	 * path at save time - it's stored as-is and the UI just degrades to
	 * view-only until the underlying filesystem state is fixed. Every
	 * actual use of these paths (showSetup(), __writeRobotsTxt(),
	 * __tailAccessLogForWebsite()) re-validates live rather than trusting
	 * this save-time state, since permissions/symlinks can change after.
	 */
	function saveSiteAccessConfig($info) {
		checkAdminLoggedIn();
		$websiteId = intval($info['website_id'] ?? 0);

		if ($websiteId) {
			$dataList = [
				'website_id|int' => $websiteId,
				'docroot_path' => !empty($info['docroot_path']) ? trim($info['docroot_path']) : 'NULL',
				'access_log_path' => !empty($info['access_log_path']) ? trim($info['access_log_path']) : 'NULL',
				'updated_at' => 'NOW()',
			];

			$existing = $this->dbHelper->getRow('ai_visibility_site_access', "website_id=$websiteId");
			if (!empty($existing)) {
				$this->dbHelper->updateRow('ai_visibility_site_access', $dataList, "website_id=$websiteId");
			} else {
				$dataList['created_at'] = 'NOW()';
				$this->dbHelper->insertRow('ai_visibility_site_access', $dataList);
			}
		}

		$this->showSetup(['website_id' => $websiteId]);
	}

	// func to toggle whether a platform is blocked in this website's
	// robots.txt - owner-level (any logged-in user managing their own
	// website), writes to disk only when the admin-configured docroot is
	// currently valid+writable; a write failure is surfaced, never silent
	function toggleRobotsRule($info) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		$platform = !empty($info['platform']) ? trim($info['platform']) : '';

		$result = $this->__toggleRobotsRuleForWebsite($websiteId, $platform, $userId);
		if (!empty($result['ok']) && !empty($result['error'])) {
			$this->set('robotsWriteError', $result['error']);
		}

		$this->showSetup(['website_id' => $websiteId]);
	}

	/**
	 * Core toggle-a-platform's-robots.txt-rule write logic, shared by the
	 * web form (toggleRobotsRule() above) and the MCP toggle_robots_rule
	 * tool (MCPController::toolToggleRobotsRule()). Does NOT check website
	 * ownership - every caller must do that first (the web path already
	 * does via __resolveWebsiteId() cross-checking the session's own
	 * website list; MCP does via __assertOwnsWebsite()).
	 */
	function __toggleRobotsRuleForWebsite($websiteId, $platform, $changedBy) {
		$websiteId = intval($websiteId);
		$platform = trim($platform);

		$platformInfo = $platform !== '' ? $this->dbHelper->getRow('ai_platforms', "platform='" . addslashes($platform) . "' and bot_ua_pattern is not null and bot_ua_pattern != ''") : null;
		if (empty($platformInfo)) {
			return ['ok' => false, 'is_blocked' => null, 'error' => 'Unknown platform'];
		}

		$existing = $this->dbHelper->getRow('ai_visibility_robots_rules', "website_id=$websiteId and platform='" . addslashes($platform) . "'");
		// absence of a row means "allowed" (default), so with no
		// existing row the first toggle moves it to blocked
		$nextBlocked = empty($existing) ? 1 : (empty($existing['is_blocked']) ? 1 : 0);

		if (!empty($existing)) {
			$this->dbHelper->updateRow('ai_visibility_robots_rules', ['is_blocked|int' => $nextBlocked, 'updated_at' => 'NOW()'], "website_id=$websiteId and platform='" . addslashes($platform) . "'");
		} else {
			$this->dbHelper->insertRow('ai_visibility_robots_rules', [
				'website_id|int' => $websiteId,
				'platform' => $platform,
				'is_blocked|int' => $nextBlocked,
				'updated_at' => 'NOW()',
			]);
		}

		// append-only compliance record - never updated/deleted, unlike
		// the current-state row above (see exportRobotsAuditLog())
		$this->dbHelper->insertRow('ai_visibility_robots_audit_log', [
			'website_id|int' => $websiteId,
			'platform' => $platform,
			'is_blocked|int' => $nextBlocked,
			'changed_by|int' => $changedBy,
			'changed_at' => 'NOW()',
		]);

		$error = null;
		$docrootStatus = $this->__validateDocrootPath($this->__getSiteAccessConfig($websiteId)['docroot_path'] ?? null);
		if (!empty($docrootStatus['writable'])) {
			$writeResult = $this->__writeRobotsTxt($websiteId);
			if (empty($writeResult['ok'])) {
				$error = $writeResult['error'];
			}
		}

		return ['ok' => true, 'is_blocked' => $nextBlocked, 'error' => $error];
	}

	// func to (re)generate llms.txt from data SEO Panel already has about
	// this website - owner-level, two-step confirm if an existing file
	// wasn't generated by SEO Panel (never silently overwrite hand-authored content)
	function regenerateLlmsTxt($info) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);

		$result = $this->__regenerateLlmsTxtForWebsite($websiteId, !empty($info['confirm_overwrite']));
		if (!empty($result['confirm_needed'])) {
			$this->set('llmsConfirmNeeded', true);
		} elseif (!empty($result['error'])) {
			$this->set('llmsWriteError', $result['error']);
		}

		$this->showSetup(['website_id' => $websiteId]);
	}

	/**
	 * Core llms.txt regeneration logic, shared by the web form
	 * (regenerateLlmsTxt() above) and the MCP regenerate_llms_txt tool.
	 * Does NOT check website ownership - every caller must do that first.
	 * Strictly safer than the .htaccess writer for MCP exposure: worst
	 * case on failure is a wrong STATIC file (never served with special
	 * meaning by any web server), not a 500'd site - so no self-test/
	 * rollback safety net is needed here the way __writeHtaccessRules() has.
	 */
	function __regenerateLlmsTxtForWebsite($websiteId, $confirmOverwrite) {
		$websiteId = intval($websiteId);
		$accessInfo = $this->__getSiteAccessConfig($websiteId);
		$docrootStatus = !empty($accessInfo['docroot_path']) ? $this->__validateDocrootPath($accessInfo['docroot_path']) : null;

		if (empty($docrootStatus['writable'])) {
			return ['ok' => false, 'confirm_needed' => false, 'error' => 'No writable document root configured for this website.'];
		}

		$llmsPath = $docrootStatus['real'] . '/llms.txt';

		if (file_exists($llmsPath) && !$confirmOverwrite) {
			$existingContent = @file_get_contents($llmsPath);
			if ($existingContent === false || strpos($existingContent, self::LLMS_TXT_MARKER) === false) {
				return ['ok' => false, 'confirm_needed' => true, 'error' => null];
			}
		}

		$content = $this->__buildLlmsTxtContent($websiteId);
		if (@file_put_contents($llmsPath, $content, LOCK_EX) === false) {
			return ['ok' => false, 'confirm_needed' => false, 'error' => 'Could not write llms.txt - check filesystem permissions.'];
		}

		return ['ok' => true, 'confirm_needed' => false, 'error' => null];
	}

	# func to fetch this website's ai_visibility_site_access row, if any
	function __getSiteAccessConfig($websiteId) {
		return $this->dbHelper->getRow('ai_visibility_site_access', "website_id=" . intval($websiteId));
	}

	/**
	 * Validates an admin-entered local docroot path. Must resolve via
	 * realpath(), be a real directory, and must NOT resolve inside SEO
	 * Panel's own install (either direction) - this feature is meant to
	 * point at a DIFFERENT website's docroot, and containing it stops the
	 * feature from being (mis)used to overwrite SEO Panel's own files.
	 * Reuses the realpath+containment idiom from libs/onlineupgrade.class.php.
	 * Always re-run live at point of use - never trust a stale save-time result.
	 */
	function __validateDocrootPath($path) {
		if (empty($path)) {
			return ['ok' => false, 'writable' => false, 'real' => null, 'error' => 'Not configured'];
		}

		$real = realpath($path);
		if ($real === false) {
			return ['ok' => false, 'writable' => false, 'real' => null, 'error' => 'Path does not exist'];
		}
		if (!is_dir($real)) {
			return ['ok' => false, 'writable' => false, 'real' => null, 'error' => 'Not a directory'];
		}

		$spRoot = realpath(SP_ABSPATH);
		if ($spRoot !== false) {
			$realNorm = str_replace('\\', '/', $real) . '/';
			$spRootNorm = str_replace('\\', '/', $spRoot) . '/';
			if (strpos($realNorm, $spRootNorm) === 0 || strpos($spRootNorm, $realNorm) === 0) {
				return ['ok' => false, 'writable' => false, 'real' => null, 'error' => 'Path overlaps the SEO Panel install itself'];
			}
		}

		return ['ok' => true, 'writable' => is_writable($real), 'real' => $real, 'error' => null];
	}

	// func to validate an admin-entered access log path (Feature B) - same
	// containment rule as __validateDocrootPath(), but for a readable FILE
	function __validateAccessLogPath($path) {
		if (empty($path)) {
			return ['ok' => false, 'readable' => false, 'real' => null, 'error' => 'Not configured'];
		}

		$real = realpath($path);
		if ($real === false) {
			return ['ok' => false, 'readable' => false, 'real' => null, 'error' => 'Path does not exist'];
		}
		if (!is_file($real)) {
			return ['ok' => false, 'readable' => false, 'real' => null, 'error' => 'Not a file'];
		}

		$spRoot = realpath(SP_ABSPATH);
		if ($spRoot !== false) {
			$realNorm = str_replace('\\', '/', $real);
			$spRootNorm = str_replace('\\', '/', $spRoot) . '/';
			if (strpos($realNorm . '/', $spRootNorm) === 0) {
				return ['ok' => false, 'readable' => false, 'real' => null, 'error' => 'Path overlaps the SEO Panel install itself'];
			}
		}

		return ['ok' => true, 'readable' => is_readable($real), 'real' => $real, 'error' => null];
	}

	// func to fetch a website's live robots.txt over HTTP for the always-shown
	// read-only preview - works for any site, co-located or not. Short
	// timeout since this runs synchronously on Setup screen render.
	function __fetchRobotsTxtPreview($websiteUrl) {
		$urlParts = parse_url($websiteUrl);
		if (empty($urlParts['host'])) {
			return null;
		}
		$scheme = !empty($urlParts['scheme']) ? $urlParts['scheme'] : 'http';
		$robotsUrl = "$scheme://{$urlParts['host']}/robots.txt";

		$spider = new Spider();
		$spider->_CURLOPT_TIMEOUT = 5;
		$result = $spider->getContent($robotsUrl, false, false);

		return !empty($result['page']) ? $result['page'] : null;
	}

	// func to strip a previously-written SEO-Panel-managed block (delimited
	// by $begin/$end) from file content, leaving everything else untouched -
	// shared by every managed-block writer (__writeRobotsTxt(),
	// __writeHtaccessRules()) so the strip regex is defined exactly once
	function __stripManagedBlock($content, $begin, $end) {
		$pattern = '/\n?' . preg_quote($begin, '/') . '.*?' . preg_quote($end, '/') . '\n?/s';
		return preg_replace($pattern, "\n", (string)$content);
	}

	// func to strip the robots.txt managed block specifically - thin
	// wrapper over __stripManagedBlock() for existing call sites
	function __stripManagedRobotsBlock($content) {
		return $this->__stripManagedBlock($content, self::ROBOTS_BLOCK_BEGIN, self::ROBOTS_BLOCK_END);
	}

	/**
	 * Rewrites this website's robots.txt to reflect the current
	 * ai_visibility_robots_rules toggle state, touching only the clearly
	 * delimited managed block - everything else in the file (sitemap
	 * directives, other User-agent blocks, etc.) survives untouched.
	 * Single fopen('c+')+flock(LOCK_EX) spanning the whole
	 * read-strip-append-truncate-write sequence, not separate
	 * file_get_contents/file_put_contents calls, so two concurrent toggles
	 * can't race and corrupt/duplicate the block.
	 */
	function __writeRobotsTxt($websiteId) {
		$accessInfo = $this->__getSiteAccessConfig($websiteId);
		$docrootStatus = !empty($accessInfo['docroot_path']) ? $this->__validateDocrootPath($accessInfo['docroot_path']) : null;
		if (empty($docrootStatus['writable'])) {
			return ['ok' => false, 'error' => 'Document root is not currently writable'];
		}

		$robotsPath = $docrootStatus['real'] . '/robots.txt';

		$fh = @fopen($robotsPath, 'c+');
		if ($fh === false) {
			return ['ok' => false, 'error' => 'Could not open robots.txt for writing'];
		}
		if (!flock($fh, LOCK_EX)) {
			fclose($fh);
			return ['ok' => false, 'error' => 'Could not lock robots.txt'];
		}

		$existing = stream_get_contents($fh);
		$stripped = rtrim($this->__stripManagedRobotsBlock($existing));

		$ruleRows = $this->db->select("SELECT platform, is_blocked FROM ai_visibility_robots_rules WHERE website_id=" . intval($websiteId) . " AND is_blocked=1");
		$blockedPatterns = [];
		if (!empty($ruleRows)) {
			$platformCsv = "'" . implode("','", array_map(function($r) { return addslashes($r['platform']); }, $ruleRows)) . "'";
			// DISTINCT: a platform (e.g. chatgpt) can have multiple ai_platforms
			// rows (chatgpt.com, chat.openai.com) sharing one robots token.
			// COALESCE(NULLIF(robots_user_agent_token,''), bot_ua_pattern):
			// robots_user_agent_token is the crawler's own documented
			// robots.txt User-agent token when it differs from
			// bot_ua_pattern (a substring match used elsewhere for
			// classifying raw User-Agent headers) - falls back to
			// bot_ua_pattern when not explicitly set, unchanged behavior
			// for every platform that hasn't set an override.
			$platformInfoRows = $this->db->select("SELECT DISTINCT COALESCE(NULLIF(robots_user_agent_token,''), bot_ua_pattern) AS robots_token FROM ai_platforms WHERE platform IN ($platformCsv) AND bot_ua_pattern IS NOT NULL AND bot_ua_pattern != ''");
			foreach ($platformInfoRows as $row) {
				$blockedPatterns[] = $row['robots_token'];
			}
		}

		$block = self::ROBOTS_BLOCK_BEGIN . "\n";
		foreach ($blockedPatterns as $pattern) {
			$block .= "User-agent: $pattern\nDisallow: /\n";
		}
		$block .= self::ROBOTS_BLOCK_END;

		$newContent = ($stripped !== '' ? $stripped . "\n\n" : '') . $block . "\n";

		ftruncate($fh, 0);
		rewind($fh);
		fwrite($fh, $newContent);
		fflush($fh);
		flock($fh, LOCK_UN);
		fclose($fh);

		return ['ok' => true, 'error' => null];
	}

	// func to save which file extensions get the AI-bot X-Robots-Tag header,
	// then apply it - owner-level (the admin already authorized the docroot
	// by configuring it; the owner just picks which extensions get the header)
	function saveHtaccessConfig($info) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);

		$extensions = !empty($info['htaccess_extensions']) && is_array($info['htaccess_extensions'])
			? array_intersect($info['htaccess_extensions'], ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])
			: [];
		$enabled = !empty($info['htaccess_ai_headers_enabled']) && !empty($extensions);

		$this->dbHelper->updateRow('ai_visibility_site_access', [
			'htaccess_ai_headers_enabled|int' => $enabled ? 1 : 0,
			'htaccess_extensions' => implode(',', $extensions),
			'updated_at' => 'NOW()',
		], "website_id=" . intval($websiteId));

		$writeResult = $this->__writeHtaccessRules($websiteId, $userId);
		if (empty($writeResult['ok'])) {
			$this->set('htaccessWriteError', $writeResult['error']);
		}

		$this->showSetup(['website_id' => $websiteId]);
	}

	/**
	 * Rewrites this website's .htaccess to add (or remove) an X-Robots-Tag
	 * header for admin/owner-selected file extensions, inside a clearly
	 * delimited managed block - same containment guarantee as
	 * __writeRobotsTxt(), but with a real safety net on top since a
	 * malformed .htaccess can 500 an ENTIRE live site, unlike robots.txt
	 * (inert if wrong): a baseline self-test before touching anything (so a
	 * site that's already down is never blamed on this write), and a
	 * post-write self-test with automatic rollback if the new rules broke
	 * it. No apachectl configtest/shell-out anywhere in this codebase - a
	 * live HTTP fetch is both the safest and the earliest possible signal,
	 * since Apache doesn't re-parse .htaccess until the next real request
	 * anyway. Every write/rollback is durably logged (see
	 * ai_visibility_htaccess_audit_log) given the stakes.
	 */
	function __writeHtaccessRules($websiteId, $changedBy) {
		$accessInfo = $this->__getSiteAccessConfig($websiteId);
		$docrootStatus = !empty($accessInfo['docroot_path']) ? $this->__validateDocrootPath($accessInfo['docroot_path']) : null;
		if (empty($docrootStatus['writable'])) {
			return ['ok' => false, 'error' => 'Document root is not currently writable'];
		}

		$websiteInfo = $this->dbHelper->getRow('websites', "id=" . intval($websiteId));
		if (empty($websiteInfo['url'])) {
			return ['ok' => false, 'error' => 'No website URL to verify against'];
		}

		$extensions = !empty($accessInfo['htaccess_extensions']) ? explode(',', $accessInfo['htaccess_extensions']) : [];
		$enabled = !empty($accessInfo['htaccess_ai_headers_enabled']);

		// baseline self-test BEFORE touching anything - if the site is
		// already unreachable we can't tell "we broke it" from "already
		// broken", and writing+rolling-back would just add churn on top of
		// a pre-existing outage
		$baseline = $this->__selfTestWebsite($websiteInfo['url']);
		if (empty($baseline['ok'])) {
			return ['ok' => false, 'error' => $this->spTextAIV['htaccessalreadydown'] ?? 'Your site is not currently reachable, so SEO Panel cannot safely verify a change. No changes were made.'];
		}

		$htaccessPath = $docrootStatus['real'] . '/.htaccess';
		$backupPath = $htaccessPath . '.seopanel-backup';

		$fh = @fopen($htaccessPath, 'c+');
		if ($fh === false) {
			return ['ok' => false, 'error' => 'Could not open .htaccess for writing'];
		}
		if (!flock($fh, LOCK_EX)) {
			fclose($fh);
			return ['ok' => false, 'error' => 'Could not lock .htaccess'];
		}

		$original = stream_get_contents($fh);
		// belt-and-suspenders: survives the PHP process dying mid-request
		// (e.g. hitting max_execution_time between write and verify below),
		// after which the in-memory $original would otherwise be unrecoverable
		@file_put_contents($backupPath, $original, LOCK_EX);

		$stripped = rtrim($this->__stripManagedBlock($original, self::HTACCESS_BLOCK_BEGIN, self::HTACCESS_BLOCK_END));

		$newContent = $stripped;
		if ($enabled && !empty($extensions)) {
			$extPattern = implode('|', array_map(function($e) { return preg_quote($e, '/'); }, $extensions));
			$block = self::HTACCESS_BLOCK_BEGIN . "\n"
				. "<FilesMatch \"\\.($extPattern)$\">\n"
				. "\tHeader set X-Robots-Tag \"noai\"\n"
				. "</FilesMatch>\n"
				. self::HTACCESS_BLOCK_END;
			$newContent = ($stripped !== '' ? $stripped . "\n\n" : '') . $block . "\n";
		}

		ftruncate($fh, 0);
		rewind($fh);
		fwrite($fh, $newContent);
		fflush($fh);

		// post-write self-test - the new rules are live on disk now, lock
		// still held so no concurrent request can interleave
		$postWrite = $this->__selfTestWebsite($websiteInfo['url']);

		if (empty($postWrite['ok'])) {
			ftruncate($fh, 0);
			rewind($fh);
			fwrite($fh, $original);
			fflush($fh);
			flock($fh, LOCK_UN);
			fclose($fh);

			$this->dbHelper->insertRow('ai_visibility_htaccess_audit_log', [
				'website_id|int' => $websiteId,
				'action' => 'rollback',
				'extensions' => implode(',', $extensions),
				'self_test_http_code|int' => $postWrite['http_code'],
				'self_test_ok|int' => 0,
				'changed_by|int' => $changedBy,
				'changed_at' => 'NOW()',
			]);
			$this->dbHelper->updateRow('ai_visibility_site_access', [
				'htaccess_last_error' => $this->spTextAIV['htaccessrollback'] ?? 'The new rules made your site unreachable and were automatically reverted. No changes were kept.',
			], "website_id=" . intval($websiteId));

			return ['ok' => false, 'error' => $this->spTextAIV['htaccessrollback'] ?? 'The new rules made your site unreachable and were automatically reverted. No changes were kept.'];
		}

		flock($fh, LOCK_UN);
		fclose($fh);
		@unlink($backupPath);

		$this->dbHelper->insertRow('ai_visibility_htaccess_audit_log', [
			'website_id|int' => $websiteId,
			'action' => 'write',
			'extensions' => implode(',', $extensions),
			'self_test_http_code|int' => $postWrite['http_code'],
			'self_test_ok|int' => 1,
			'changed_by|int' => $changedBy,
			'changed_at' => 'NOW()',
		]);
		$this->dbHelper->updateRow('ai_visibility_site_access', [
			'htaccess_last_written_at' => 'NOW()',
			'htaccess_last_error' => 'NULL',
		], "website_id=" . intval($websiteId));

		return ['ok' => true, 'error' => null];
	}

	// func to fetch a website's own homepage as a liveness check (cache-
	// busted, since a CDN/reverse-proxy could otherwise mask the real
	// origin state) - used by __writeHtaccessRules() both before (baseline)
	// and after (verify) a write. Short timeout: this blocks the request
	// that triggered it, twice, so it must stay well under PHP's
	// max_execution_time.
	function __selfTestWebsite($websiteUrl) {
		$cacheBustedUrl = $websiteUrl . (strpos($websiteUrl, '?') === false ? '?' : '&') . 'spcheck=' . time();
		$spider = new Spider();
		$spider->_CURLOPT_TIMEOUT = 8;
		$spider->_CURL_HTTPHEADER = ['Cache-Control: no-cache'];
		$result = $spider->getContent($cacheBustedUrl, false, false);
		$httpCode = intval($result['http_code'] ?? 0);
		$ok = empty($result['error']) && $httpCode > 0 && $httpCode < 500;
		return ['ok' => $ok, 'http_code' => $httpCode];
	}

	/**
	 * Builds llms.txt content from data SEO Panel already has about this
	 * website (title/description/keywords, Site Auditor's crawled pages) -
	 * the on-premise differentiator: a SaaS tool would need fresh crawling
	 * or manual input for this, SEO Panel already has it sitting in its own DB.
	 */
	function __buildLlmsTxtContent($websiteId) {
		$websiteId = intval($websiteId);
		$websiteInfo = $this->dbHelper->getRow('websites', "id=$websiteId");

		$lines = [self::LLMS_TXT_MARKER, ''];
		$lines[] = '# ' . (!empty($websiteInfo['title']) ? $websiteInfo['title'] : $websiteInfo['name']);
		$lines[] = '';
		if (!empty($websiteInfo['description'])) {
			$lines[] = '> ' . $websiteInfo['description'];
			$lines[] = '';
		}

		$projectInfo = $this->dbHelper->getRow('auditorprojects', "website_id=$websiteId");
		if (!empty($projectInfo['id'])) {
			$pages = $this->db->select("SELECT page_url, page_title, page_description FROM auditorreports WHERE project_id=" . intval($projectInfo['id']) . " ORDER BY pagerank DESC LIMIT 50");
			if (!empty($pages)) {
				$lines[] = '## Pages';
				$lines[] = '';
				foreach ($pages as $page) {
					$title = !empty($page['page_title']) ? $page['page_title'] : $page['page_url'];
					$desc = !empty($page['page_description']) ? ': ' . trim(preg_replace('/\s+/', ' ', $page['page_description'])) : '';
					$lines[] = "- [$title]({$page['page_url']})$desc";
				}
				$lines[] = '';
			}
		}

		return implode("\n", $lines);
	}

	/**
	 * Generates the downloadable AI bot collector script for a website.
	 * Called only from aibot-collector.php (logged-in gated - this produces
	 * a file the site owner takes away and hosts on their OWN server, it is
	 * not itself served to the public). Dependency-free, no remote includes
	 * (a remote-includable snippet would be a code-execution risk for
	 * whoever installs it) - just UA prefilter, FCrDNS, and a short-timeout
	 * POST that fails silently so it can never break the host site.
	 *
	 * Classification into a named platform happens server-side at ingest
	 * (see ingestBotHit()), not in this script, so the UA prefilter here is
	 * deliberately broad/generic and never needs to be re-downloaded when
	 * new bots emerge - only the "should I bother with a DNS lookup at all"
	 * decision is static.
	 */
	function generateBotCollectorScript($websiteId) {
		$siteInfo = $this->dbHelper->getRow('ai_visibility_sites', "website_id=" . intval($websiteId));
		$token = !empty($siteInfo['token']) ? $siteInfo['token'] : '';
		$collectUrl = SP_WEBPATH . "/aibot-collect.php";

		$token = addslashes($token);
		$collectUrl = addslashes($collectUrl);

		return <<<PHP
<?php
/**
 * SEO Panel - AI Bot Crawler Collector
 *
 * Detects AI crawler visits (GPTBot, ClaudeBot, PerplexityBot, and others)
 * server-side, since these bots never execute JavaScript. Include this file
 * at the very top of your site's bootstrap (e.g. the first line of
 * index.php or wp-config.php; for WordPress, dropping it into
 * wp-content/mu-plugins/ loads it automatically on every request).
 *
 * This file never breaks your site: it does nothing at all for normal
 * traffic, and any failure (DNS, network, whatever) is silently swallowed.
 */

\$__aiv_ua = isset(\$_SERVER['HTTP_USER_AGENT']) ? \$_SERVER['HTTP_USER_AGENT'] : '';

// Broad, generic prefilter - deliberately not tied to a specific vendor
// list so this file never goes stale. Precise classification happens
// server-side at SEO Panel, this just decides whether to bother at all.
if (\$__aiv_ua !== '' && preg_match('/bot|crawler|spider|agent/i', \$__aiv_ua)) {
	try {
		\$__aiv_ip = isset(\$_SERVER['REMOTE_ADDR']) ? \$_SERVER['REMOTE_ADDR'] : '';
		\$__aiv_verified = false;

		if (\$__aiv_ip !== '') {
			// FCrDNS: reverse-DNS the IP, then forward-confirm it resolves
			// back to the same IP - the same method used to verify
			// Googlebot. Done here, not at SEO Panel, because this is the
			// only point where the real crawler IP is known with certainty.
			//
			// gethostbyaddr()/gethostbyname() have no timeout parameter of
			// their own and go through the OS resolver, so a slow/dead
			// nameserver could otherwise stall every request whose UA loosely
			// matches the prefilter above. default_socket_timeout is the
			// closest lever userland PHP has for this - not honored by every
			// resolver backend, but a real bound on most - so this caps it
			// best-effort and always restores the host's own setting after.
			\$__aiv_prevTimeout = ini_get('default_socket_timeout');
			ini_set('default_socket_timeout', 2);
			try {
				\$__aiv_host = @gethostbyaddr(\$__aiv_ip);
				if (\$__aiv_host && \$__aiv_host !== \$__aiv_ip) {
					\$__aiv_verified = (@gethostbyname(\$__aiv_host) === \$__aiv_ip);
				}
			} finally {
				ini_set('default_socket_timeout', \$__aiv_prevTimeout);
			}
		}

		\$__aiv_path = isset(\$_SERVER['REQUEST_URI']) ? strtok(\$_SERVER['REQUEST_URI'], '?') : '/';

		\$__aiv_payload = json_encode(array(
			't' => '$token',
			'ua' => \$__aiv_ua,
			'verified' => \$__aiv_verified,
			'u' => \$__aiv_path,
		));

		\$__aiv_ctx = stream_context_create(array('http' => array(
			'method' => 'POST',
			'header' => "Content-Type: application/json\\r\\n",
			'content' => \$__aiv_payload,
			'timeout' => 2,
			'ignore_errors' => true,
		)));
		@file_get_contents('$collectUrl', false, \$__aiv_ctx);
	} catch (Throwable \$__aiv_e) {
		// never let a collector failure affect the host site
	}
}
PHP;
	}

	/**
	 * Zero-touch install: writes the same content generateBotCollectorScript()
	 * produces directly into the co-located site's wp-content/mu-plugins/ -
	 * WordPress auto-loads every PHP file there on every request, no
	 * activation step needed. Removes the last manual "download this file
	 * and paste it into your site" step for the one CMS this can be
	 * detected and automated for. Owner-level (same ownership check as
	 * toggleRobotsRule()) - only offered when an admin has already
	 * authorized a writable docroot for this website.
	 */
	function installWordPressCollector($info) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);

		$accessInfo = $this->__getSiteAccessConfig($websiteId);
		$docrootStatus = !empty($accessInfo['docroot_path']) ? $this->__validateDocrootPath($accessInfo['docroot_path']) : null;

		if (empty($docrootStatus['writable']) || !$this->__detectWordPress($docrootStatus['real'])) {
			$this->set('wpInstallError', $this->spTextAIV['wpinstallfailed'] ?? 'Could not write the collector to wp-content/mu-plugins/ - check filesystem permissions.');
			$this->showSetup(['website_id' => $websiteId]);
			return;
		}

		$muPluginsDir = $docrootStatus['real'] . '/wp-content/mu-plugins';
		if (!is_dir($muPluginsDir) && !@mkdir($muPluginsDir, 0755, true)) {
			$this->set('wpInstallError', $this->spTextAIV['wpinstallfailed'] ?? 'Could not write the collector to wp-content/mu-plugins/ - check filesystem permissions.');
			$this->showSetup(['website_id' => $websiteId]);
			return;
		}

		$content = $this->generateBotCollectorScript($websiteId);
		$targetPath = $muPluginsDir . '/seo-panel-ai-bot-collector.php';
		if (@file_put_contents($targetPath, $content, LOCK_EX) === false) {
			$this->set('wpInstallError', $this->spTextAIV['wpinstallfailed'] ?? 'Could not write the collector to wp-content/mu-plugins/ - check filesystem permissions.');
		}

		$this->showSetup(['website_id' => $websiteId]);
	}

	// func to detect WordPress at a validated, resolved docroot path
	function __detectWordPress($docrootReal) {
		return !empty($docrootReal) && is_file($docrootReal . '/wp-config.php');
	}

	// func to check whether the zero-touch mu-plugin install has already been done
	function __isWpCollectorInstalled($docrootReal) {
		return !empty($docrootReal) && is_file($docrootReal . '/wp-content/mu-plugins/seo-panel-ai-bot-collector.php');
	}

	# func to poll install status (AJAX) - waiting for first hit vs receiving data
	function showInstallStatus($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);

		$siteInfo = empty($websiteId) ? null : $this->dbHelper->getRow('ai_visibility_sites', "website_id=$websiteId");

		header('Content-Type: application/json');
		echo json_encode([
			'status' => !empty($siteInfo['last_seen_at']) ? 'receiving' : 'waiting',
			'last_seen_at' => !empty($siteInfo['last_seen_at']) ? $siteInfo['last_seen_at'] : null,
			'bot_status' => !empty($siteInfo['bot_last_seen_at']) ? 'receiving' : 'waiting',
			'bot_last_seen_at' => !empty($siteInfo['bot_last_seen_at']) ? $siteInfo['bot_last_seen_at'] : null,
		]);
		exit;
	}

	# func to show the referral report - time series by platform, top landing pages, platform breakdown
	function showReport($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$this->set('websiteList', $websiteList);

		if (empty($websiteList)) {
			$this->set('spTextWebsite', $this->getLanguageTexts('website', $_SESSION['lang_code']));
			$this->render('dashboard/no_websites');
			return;
		}

		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		$this->set('websiteId', $websiteId);

		$fromTime = !empty($info['from_time']) ? $info['from_time'] : date('Y-m-d', strtotime('-30 days'));
		$toTime = !empty($info['to_time']) ? $info['to_time'] : date('Y-m-d');
		$this->set('fromTime', $fromTime);
		$this->set('toTime', $toTime);

		$fromTimeSql = addslashes($fromTime);
		$toTimeSql = addslashes($toTime);

		$sql = "select platform, hit_date, sum(hits) as hits from ai_referrals
				where website_id=$websiteId and hit_date >= '$fromTimeSql' and hit_date <= '$toTimeSql'
				group by platform, hit_date order by hit_date";
		$timeSeriesList = $this->db->select($sql);

		// platform totals for the breakdown table, also doubles as the chart's series list
		$platformTotals = [];
		foreach ($timeSeriesList as $row) {
			$platformTotals[$row['platform']] = ($platformTotals[$row['platform']] ?? 0) + intval($row['hits']);
		}
		arsort($platformTotals);
		$this->set('platformTotals', $platformTotals);

		$sql2 = "select url_path, sum(hits) as hits from ai_referrals
				 where website_id=$websiteId and hit_date >= '$fromTimeSql' and hit_date <= '$toTimeSql'
				 group by url_path order by hits desc limit 25";
		$this->set('topPages', $this->db->select($sql2));

		$graphContent = '';
		if (!empty($timeSeriesList)) {
			$platforms = array_keys($platformTotals);
			$matrix = []; // hit_date => platform => hits
			foreach ($timeSeriesList as $row) {
				$matrix[$row['hit_date']][$row['platform']] = intval($row['hits']);
			}
			$dates = array_keys($matrix);
			sort($dates);

			$header = "['" . $_SESSION['text']['common']['Date'] . "'";
			foreach ($platforms as $platform) {
				$header .= ", '" . addslashes($platform) . "'";
			}
			$header .= "]";

			$dataArr = $header;
			foreach ($dates as $date) {
				$dataArr .= ", ['$date'";
				foreach ($platforms as $platform) {
					$dataArr .= ", " . intval($matrix[$date][$platform] ?? 0);
				}
				$dataArr .= "]";
			}

			$this->set('dataArr', $dataArr);
			$this->set('graphTitle', $this->spTextAIV['Referrals over time']);
			$graphContent = $this->getViewContent('report/graph');
		} else {
			$graphContent = showErrorMsg($_SESSION['text']['common']['No Records Found'], false, true);
		}
		$this->set('graphContent', $graphContent);

		$this->render('aivisibility/report');
	}

	# func to export the AI Referral report (daily hits by platform, same range as showReport()) as CSV
	function exportReportCsv($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		if (empty($websiteId)) {
			exit;
		}

		$fromTime = !empty($info['from_time']) ? $info['from_time'] : date('Y-m-d', strtotime('-30 days'));
		$toTime = !empty($info['to_time']) ? $info['to_time'] : date('Y-m-d');
		$fromTimeSql = addslashes($fromTime);
		$toTimeSql = addslashes($toTime);

		$sql = "select hit_date, platform, sum(hits) as hits from ai_referrals
				where website_id=$websiteId and hit_date >= '$fromTimeSql' and hit_date <= '$toTimeSql'
				group by hit_date, platform order by hit_date, platform";
		$rowList = $this->db->select($sql);

		$this->__streamCsv("ai-referrals-$websiteId-$fromTime-to-$toTime.csv", ['Date', 'Platform', 'Referrals'], $rowList, ['hit_date', 'platform', 'hits']);
	}

	/**
	 * AI Overview tab: website-wide summary of Google AI Overview presence
	 * and citation, built entirely from data the AI Overview Tracking
	 * feature already collects (searchresults.aio_* + aio_references) via
	 * the scheduled rank-check cron - no new ingest, purely a different
	 * (website-level, not per-keyword-report-row) presentation of it.
	 */
	// func to summarize a list of aio_present/aio_cited/aio_supported rows
	// (one row per keyword's latest measured check) into present/cited/
	// unsupported counts - shared by the full AI Overview report and the
	// AI Visibility Overview dashboard so both show the exact same numbers.
	function __summarizeAioRows($rowList) {
		$summary = ['measured' => 0, 'present' => 0, 'cited' => 0, 'unsupported' => 0];
		foreach ($rowList as $row) {
			$summary['measured']++;
			if (intval($row['aio_supported']) === 0) {
				$summary['unsupported']++;
				continue;
			}
			if (!empty($row['aio_present'])) $summary['present']++;
			if (!empty($row['aio_cited'])) $summary['cited']++;
		}
		return $summary;
	}

	// func to compute a website's AI Overview summary without the extra
	// keyword/search-engine columns showAIOverviewReport()'s per-row table
	// needs - used by the lighter Overview dashboard and the MCP
	// get_ai_overview_summary tool, both of which only need the totals.
	function __getAioSummaryForWebsite($websiteId) {
		$websiteId = intval($websiteId);
		$sql = "SELECT s.aio_present, s.aio_cited, s.aio_supported
				FROM searchresults s
				JOIN keywords k ON k.id = s.keyword_id
				WHERE k.website_id = $websiteId AND k.status = 1 AND s.aio_checked_at IS NOT NULL
				AND s.id = (
					SELECT s2.id FROM searchresults s2
					WHERE s2.keyword_id = s.keyword_id AND s2.searchengine_id = s.searchengine_id
					AND s2.aio_checked_at IS NOT NULL
					ORDER BY s2.result_date DESC, s2.id DESC LIMIT 1
				)";
		return $this->__summarizeAioRows($this->db->select($sql));
	}

	function showAIOverviewReport($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$this->set('websiteList', $websiteList);

		if (empty($websiteList)) {
			$this->set('spTextWebsite', $this->getLanguageTexts('website', $_SESSION['lang_code']));
			$this->render('dashboard/no_websites');
			return;
		}

		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		$this->set('websiteId', $websiteId);

		include_once(SP_CTRLPATH."/aioverview.ctrl.php");
		$websiteInfo = $this->dbHelper->getRow('websites', "id=$websiteId");
		$trackedDomain = !empty($websiteInfo['url']) ? AIOverviewController::registrableDomain($websiteInfo['url']) : '';
		$this->set('trackedDomain', $trackedDomain);
		$this->set('subdomainPolicy', defined('SP_AIO_SUBDOMAIN_MATCH') ? SP_AIO_SUBDOMAIN_MATCH : 'registrable');

		// latest measured (keyword, search engine) rows for this website
		$sql = "SELECT k.id AS keyword_id, k.name AS keyword_name, se.domain AS se_domain, s.*
				FROM searchresults s
				JOIN keywords k ON k.id = s.keyword_id
				JOIN searchengines se ON se.id = s.searchengine_id
				WHERE k.website_id = $websiteId AND k.status = 1 AND s.aio_checked_at IS NOT NULL
				AND s.id = (
					SELECT s2.id FROM searchresults s2
					WHERE s2.keyword_id = s.keyword_id AND s2.searchengine_id = s.searchengine_id
					AND s2.aio_checked_at IS NOT NULL
					ORDER BY s2.result_date DESC, s2.id DESC LIMIT 1
				)
				ORDER BY k.name";
		$rowList = $this->db->select($sql);
		$this->set('rowList', $rowList);
		$this->set('summary', $this->__summarizeAioRows($rowList));

		// which domains get cited across this website's keywords instead of
		// (or alongside) the tracked site, from each keyword's latest check
		$sql2 = "SELECT ar.domain, COUNT(DISTINCT ar.keyword_id) AS keyword_count, COUNT(*) AS citation_count
				 FROM aio_references ar
				 JOIN keywords k ON k.id = ar.keyword_id
				 WHERE k.website_id = $websiteId AND k.status = 1
				 AND ar.checked_date = (
					 SELECT MAX(ar2.checked_date) FROM aio_references ar2 WHERE ar2.keyword_id = ar.keyword_id
				 )
				 GROUP BY ar.domain
				 ORDER BY keyword_count DESC, citation_count DESC
				 LIMIT 25";
		$this->set('competitorDomains', $this->db->select($sql2));

		$this->render('aivisibility/aioverview');
	}

	/**
	 * AI Bot Crawler Tracking report: platform breakdown (verified vs
	 * unverified), top crawled pages, hits-over-time chart. Data comes from
	 * ai_bot_hits, populated by the downloadable collector script's POSTs
	 * to aibot-collect.php - see generateBotCollectorScript()/ingestBotHit().
	 */
	function showBotReport($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$this->set('websiteList', $websiteList);

		if (empty($websiteList)) {
			$this->set('spTextWebsite', $this->getLanguageTexts('website', $_SESSION['lang_code']));
			$this->render('dashboard/no_websites');
			return;
		}

		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		$this->set('websiteId', $websiteId);

		$fromTime = !empty($info['from_time']) ? $info['from_time'] : date('Y-m-d', strtotime('-30 days'));
		$toTime = !empty($info['to_time']) ? $info['to_time'] : date('Y-m-d');
		$this->set('fromTime', $fromTime);
		$this->set('toTime', $toTime);

		$fromTimeSql = addslashes($fromTime);
		$toTimeSql = addslashes($toTime);

		$sql = "select platform, verified, hit_date, sum(hits) as hits from ai_bot_hits
				where website_id=$websiteId and hit_date >= '$fromTimeSql' and hit_date <= '$toTimeSql'
				group by platform, verified, hit_date order by hit_date";
		$timeSeriesList = $this->db->select($sql);

		// platform totals split by verified/unverified for the breakdown table
		$platformTotals = [];
		foreach ($timeSeriesList as $row) {
			$key = $row['platform'];
			if (!isset($platformTotals[$key])) $platformTotals[$key] = ['verified' => 0, 'unverified' => 0];
			$platformTotals[$key][!empty($row['verified']) ? 'verified' : 'unverified'] += intval($row['hits']);
		}
		uasort($platformTotals, function($a, $b) {
			return ($b['verified'] + $b['unverified']) - ($a['verified'] + $a['unverified']);
		});
		$this->set('platformTotals', $platformTotals);

		$sql2 = "select url_path, sum(hits) as hits from ai_bot_hits
				 where website_id=$websiteId and hit_date >= '$fromTimeSql' and hit_date <= '$toTimeSql'
				 group by url_path order by hits desc limit 25";
		$this->set('topPages', $this->db->select($sql2));

		$graphContent = '';
		if (!empty($timeSeriesList)) {
			$platforms = array_keys($platformTotals);
			$matrix = []; // hit_date => platform => hits (verified+unverified combined for the chart)
			foreach ($timeSeriesList as $row) {
				$matrix[$row['hit_date']][$row['platform']] = ($matrix[$row['hit_date']][$row['platform']] ?? 0) + intval($row['hits']);
			}
			$dates = array_keys($matrix);
			sort($dates);

			$header = "['" . $_SESSION['text']['common']['Date'] . "'";
			foreach ($platforms as $platform) {
				$header .= ", '" . addslashes($platform) . "'";
			}
			$header .= "]";

			$dataArr = $header;
			foreach ($dates as $date) {
				$dataArr .= ", ['$date'";
				foreach ($platforms as $platform) {
					$dataArr .= ", " . intval($matrix[$date][$platform] ?? 0);
				}
				$dataArr .= "]";
			}

			$this->set('dataArr', $dataArr);
			$this->set('graphTitle', $this->spTextAIV['Bot crawls over time'] ?? 'Bot crawls over time');
			$graphContent = $this->getViewContent('report/graph');
		} else {
			$graphContent = showErrorMsg($_SESSION['text']['common']['No Records Found'], false, true);
		}
		$this->set('graphContent', $graphContent);

		$this->render('aivisibility/botreport');
	}

	# func to export the AI Bot Crawler report (daily hits by platform+verified, same range as showBotReport()) as CSV
	function exportBotReportCsv($info=[]) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);
		if (empty($websiteId)) {
			exit;
		}

		$fromTime = !empty($info['from_time']) ? $info['from_time'] : date('Y-m-d', strtotime('-30 days'));
		$toTime = !empty($info['to_time']) ? $info['to_time'] : date('Y-m-d');
		$fromTimeSql = addslashes($fromTime);
		$toTimeSql = addslashes($toTime);

		$sql = "select hit_date, platform, verified, sum(hits) as hits from ai_bot_hits
				where website_id=$websiteId and hit_date >= '$fromTimeSql' and hit_date <= '$toTimeSql'
				group by hit_date, platform, verified order by hit_date, platform";
		$rowList = $this->db->select($sql);
		foreach ($rowList as &$row) {
			$row['verified'] = !empty($row['verified']) ? 'Yes' : 'No';
		}
		unset($row);

		$this->__streamCsv("ai-bot-hits-$websiteId-$fromTime-to-$toTime.csv", ['Date', 'Platform', 'Verified', 'Crawls'], $rowList, ['hit_date', 'platform', 'verified', 'hits']);
	}

	/**
	 * Owner-level: exports this website's full robots.txt AI-crawler-rule
	 * change history as CSV - a timestamped, who-did-what record suitable
	 * as proof of AI-training-opt-out policy enforcement for legal/
	 * compliance review. Reads from the append-only
	 * ai_visibility_robots_audit_log, never the current-state
	 * ai_visibility_robots_rules table (which only holds the latest value
	 * per platform, not history).
	 */
	function exportRobotsAuditLog($info) {
		$userId = isLoggedIn();
		$websiteController = New WebsiteController();
		$websiteList = $websiteController->__getAllWebsites($userId, true);
		$websiteId = $this->__resolveWebsiteId($info, $websiteList);

		$sql = "SELECT a.changed_at, a.platform, a.is_blocked, u.userName
				FROM ai_visibility_robots_audit_log a
				LEFT JOIN users u ON u.id = a.changed_by
				WHERE a.website_id=" . intval($websiteId) . "
				ORDER BY a.changed_at DESC";
		$rowList = $this->db->select($sql);
		foreach ($rowList as &$row) {
			$row['is_blocked'] = !empty($row['is_blocked']) ? 'Blocked' : 'Allowed';
			$row['userName'] = !empty($row['userName']) ? $row['userName'] : 'unknown';
		}
		unset($row);

		$this->__streamCsv("ai-robots-audit-log-$websiteId.csv", ['Changed At', 'Platform', 'Set To', 'Changed By'], $rowList, ['changed_at', 'platform', 'is_blocked', 'userName']);
	}

	/**
	 * Admin: AI platform catalog manager - add/edit/delete/toggle the
	 * ai_platforms rows that drive both the referral snippet (client-side,
	 * is_referral_source) and bot UA classification (server-side, always
	 * gated on is_active) - see aivisibility.js.php and ingestBotHit().
	 * Lets new answer engines/crawlers be added without a code deploy.
	 * Every entry point here calls checkAdminLoggedIn() itself (redirects
	 * non-admins) since aivisibility.php as a whole is not admin-only.
	 */
	function listPlatforms($info=[]) {
		checkAdminLoggedIn();
		$this->set('platformList', $this->db->select("select * from ai_platforms order by platform, hostname"));
		$this->render('aivisibility/platforms');
	}

	function savePlatform($info) {
		checkAdminLoggedIn();
		$id = intval($info['id'] ?? 0);

		$errMsg = [];
		$errMsg['platform'] = formatErrorMsg($this->validate->checkBlank($info['platform']));
		$errMsg['hostname'] = formatErrorMsg($this->validate->checkBlank($info['hostname']));
		$errMsg['display_name'] = formatErrorMsg($this->validate->checkBlank($info['display_name']));

		if (!$this->validate->flagErr) {
			$hostname = strtolower(trim($info['hostname']));
			$dupCond = "hostname='" . addslashes($hostname) . "'" . ($id ? " and id!=$id" : "");
			$dup = $this->dbHelper->getRow('ai_platforms', $dupCond);
			if (!empty($dup)) {
				$this->validate->flagErr = TRUE;
				$errMsg['hostname'] = formatErrorMsg($this->spTextAIV['platformexistsnotice'] ?? 'A platform with this hostname already exists.');
			}
		}

		if (!$this->validate->flagErr) {
			$dataList = [
				'platform' => strtolower(trim($info['platform'])),
				'hostname' => strtolower(trim($info['hostname'])),
				'display_name' => trim($info['display_name']),
				'is_active|int' => !empty($info['is_active']) ? 1 : 0,
				'is_referral_source|int' => !empty($info['is_referral_source']) ? 1 : 0,
				'bot_ua_pattern' => !empty($info['bot_ua_pattern']) ? trim($info['bot_ua_pattern']) : 'NULL',
				'robots_user_agent_token' => !empty($info['robots_user_agent_token']) ? trim($info['robots_user_agent_token']) : 'NULL',
				'verify_suffix' => !empty($info['verify_suffix']) ? trim($info['verify_suffix']) : 'NULL',
			];

			if ($id) {
				$this->dbHelper->updateRow('ai_platforms', $dataList, "id=$id");
			} else {
				$this->dbHelper->insertRow('ai_platforms', $dataList);
			}
		} else {
			$this->set('formErrMsg', $errMsg);
			$this->set('formPost', $info);
		}

		$this->listPlatforms();
	}

	function togglePlatformField($info) {
		checkAdminLoggedIn();
		$id = intval($info['id'] ?? 0);
		$field = in_array($info['field'] ?? '', ['is_active', 'is_referral_source']) ? $info['field'] : null;

		if ($id && $field) {
			$current = $this->dbHelper->getRow('ai_platforms', "id=$id");
			if (!empty($current)) {
				$this->dbHelper->updateRow('ai_platforms', [$field . '|int' => empty($current[$field]) ? 1 : 0], "id=$id");
			}
		}

		$this->listPlatforms();
	}

	function deletePlatform($info) {
		checkAdminLoggedIn();
		$id = intval($info['id'] ?? 0);
		if ($id) {
			$this->db->query("delete from ai_platforms where id=$id");
		}
		$this->listPlatforms();
	}

	# func to lazily create (or fetch) the ai_visibility_sites row for a website
	function __getOrCreateSite($websiteId, $websiteList=[]) {
		$websiteId = intval($websiteId);
		if (empty($websiteId)) return null;

		$existing = $this->dbHelper->getRow('ai_visibility_sites', "website_id=$websiteId");
		if (!empty($existing)) {
			return $existing;
		}

		$websiteInfo = null;
		foreach ($websiteList as $w) {
			if ($w['id'] == $websiteId) { $websiteInfo = $w; break; }
		}
		if (empty($websiteInfo)) {
			$websiteInfo = $this->dbHelper->getRow('websites', "id=$websiteId");
		}
		if (empty($websiteInfo)) return null;

		include_once(SP_CTRLPATH."/aioverview.ctrl.php");
		$domain = AIOverviewController::normalizeDomain($websiteInfo['url']);
		$token = bin2hex(random_bytes(24));

		$this->dbHelper->insertRow('ai_visibility_sites', [
			'website_id|int' => $websiteId,
			'token' => $token,
			'domain' => $domain,
			'created_at' => 'NOW()',
		]);

		return $this->dbHelper->getRow('ai_visibility_sites', "website_id=$websiteId");
	}

	# func to stream a query result set as a downloaded CSV and exit - $cols maps the header row to row keys, in order
	function __streamCsv($fileName, $header, $rowList, $cols) {
		header('Content-Type: text/csv; charset=utf-8');
		header('Content-Disposition: attachment; filename="' . preg_replace('/[^A-Za-z0-9._-]/', '_', $fileName) . '"');

		$out = fopen('php://output', 'w');
		fputcsv($out, $header);
		foreach ($rowList as $row) {
			$line = [];
			foreach ($cols as $col) {
				$line[] = $row[$col] ?? '';
			}
			fputcsv($out, $line);
		}
		fclose($out);
		exit;
	}

	# func to resolve/validate the requested website_id against the user's own website list
	function __resolveWebsiteId($info, $websiteList) {
		$requested = !empty($info['website_id']) ? intval($info['website_id']) : 0;
		foreach ($websiteList as $w) {
			if ($w['id'] == $requested) return $requested;
		}
		return !empty($websiteList[0]['id']) ? intval($websiteList[0]['id']) : 0;
	}

	# func to prune referral rows past the configured retention window - called from cron.php's tail
	function pruneOldReferrals() {
		$retentionDays = defined('AIV_REFERRAL_RETENTION_DAYS') ? intval(AIV_REFERRAL_RETENTION_DAYS) : 365;
		$cutoff = date('Y-m-d', strtotime("-$retentionDays days"));
		$this->db->query("DELETE FROM ai_referrals WHERE hit_date < '$cutoff'");
	}

	# func to prune stale rate-limit window rows - called from cron.php's tail
	function pruneRateLimitBuckets() {
		$cutoff = intval(floor(time() / 60)) - 10; // keep the last 10 one-minute windows
		$this->db->query("DELETE FROM ai_visibility_rate_limit WHERE window_start < $cutoff");
	}

	# func to prune bot hit rows past the configured retention window - called from cron.php's tail
	function pruneOldBotHits() {
		$retentionDays = defined('AIB_BOT_RETENTION_DAYS') ? intval(AIB_BOT_RETENTION_DAYS) : 365;
		$cutoff = date('Y-m-d', strtotime("-$retentionDays days"));
		$this->db->query("DELETE FROM ai_bot_hits WHERE hit_date < '$cutoff'");
	}

	/**
	 * Week-over-week traffic anomaly alerts: __alertOnFirstPlatformHit()
	 * only ever fires once, the very first time a platform is seen - it has
	 * no way to flag "ChatGPT referral traffic dropped 80% this week" on an
	 * established site. Runs at most once/day (called unconditionally from
	 * cron.php's tail, same idiom as CronController::refreshAllAIInsights())
	 * against every active website's ai_referrals and ai_bot_hits totals.
	 * One Throwable from one website must never abort the rest.
	 */
	function checkTrafficAnomalies() {
		include_once(SP_CTRLPATH . "/information.ctrl.php");
		$infoCtrler = new InformationController();
		if (!empty($infoCtrler->__getTodayInformation('ai_visibility_anomaly_check'))) {
			return; // already checked today
		}

		$websiteList = $this->db->select("SELECT id, user_id, url FROM websites WHERE status=1");
		foreach ($websiteList as $websiteInfo) {
			try {
				$this->__checkTrafficAnomalyForTable($websiteInfo, 'ai_referrals', 'AI referral', 'report');
				$this->__checkTrafficAnomalyForTable($websiteInfo, 'ai_bot_hits', 'AI bot crawl', 'botreport');
			} catch (Throwable $e) {
				continue; // one website's check failing must not affect the rest
			}
		}

		$infoCtrler->updateTodayInformation('1', 'ai_visibility_anomaly_check');
	}

	// func to compare this website's last-7-days total against the
	// preceding 7 days for one table (ai_referrals or ai_bot_hits) and
	// alert on a swing past ANOMALY_THRESHOLD_PCT - ignores baselines below
	// ANOMALY_MIN_BASELINE so a jump from 2 hits to 6 doesn't fire.
	// createAlert() itself dedupes same subject+message per user per day.
	function __checkTrafficAnomalyForTable($websiteInfo, $table, $label, $reportSec) {
		$websiteId = intval($websiteInfo['id']);
		if (empty($websiteInfo['user_id'])) {
			return;
		}

		$recentFrom = date('Y-m-d', strtotime('-7 days'));
		$priorFrom = date('Y-m-d', strtotime('-14 days'));

		$recentTotal = intval($this->db->select("SELECT COALESCE(SUM(hits),0) AS total FROM $table WHERE website_id=$websiteId AND hit_date >= '$recentFrom'", true)['total']);
		$priorTotal = intval($this->db->select("SELECT COALESCE(SUM(hits),0) AS total FROM $table WHERE website_id=$websiteId AND hit_date >= '$priorFrom' AND hit_date < '$recentFrom'", true)['total']);

		if ($priorTotal < self::ANOMALY_MIN_BASELINE) {
			return;
		}

		$changePct = (($recentTotal - $priorTotal) / $priorTotal) * 100;
		if (abs($changePct) < self::ANOMALY_THRESHOLD_PCT) {
			return;
		}

		$direction = $changePct < 0 ? 'dropped' : 'increased';
		include_once(SP_CTRLPATH . "/alerts.ctrl.php");
		$alertCtrl = new AlertController();
		$alertCtrl->createAlert([
			'alert_subject' => "$label traffic $direction",
			'alert_message' => ($websiteInfo['url'] ?? 'Your website') . " $label traffic $direction " . abs(round($changePct)) . "% this week ($priorTotal -> $recentTotal) compared to the previous 7 days.",
			'alert_category' => 'reports',
			'alert_url' => SP_WEBPATH . "/aivisibility.php?website_id=$websiteId&sec=$reportSec",
		], $websiteInfo['user_id']);
	}

	/**
	 * Public beacon ingest - called only from aivisibility-collect.php.
	 * The token identifies the site, it does not authenticate the sender
	 * (see spec/plan security model). Every field here is untrusted input
	 * from an unauthenticated third-party request. Always responds 204
	 * with an empty body, whether accepted or silently dropped - no
	 * information disclosure for anything that fails validation.
	 */
	function ingestBeacon() {
		header('Content-Type: text/plain');
		http_response_code(204);

		$maxBytes = 2048;
		$contentLength = isset($_SERVER['CONTENT_LENGTH']) ? intval($_SERVER['CONTENT_LENGTH']) : 0;
		if ($contentLength > $maxBytes) {
			exit;
		}

		$rawBody = file_get_contents('php://input', false, null, 0, $maxBytes + 1);
		if (empty($rawBody) || strlen($rawBody) > $maxBytes) {
			exit;
		}

		$payload = json_decode($rawBody, true);
		if (empty($payload) || !is_array($payload)) {
			exit;
		}

		$token = isset($payload['t']) ? trim((string)$payload['t']) : '';
		$platform = isset($payload['p']) ? trim((string)$payload['p']) : '';
		$urlPath = isset($payload['u']) ? (string)$payload['u'] : '';

		if ($token === '' || strlen($token) > 64 || $platform === '') {
			exit;
		}

		$siteInfo = $this->dbHelper->getRow('ai_visibility_sites', "token='" . addslashes($token) . "'");
		if (empty($siteInfo)) {
			exit;
		}

		// Origin/Referer validation against the registered domain - not
		// bulletproof (spoofable outside a real browser), stops casual noise
		include_once(SP_CTRLPATH."/aioverview.ctrl.php");
		$originHeader = !empty($_SERVER['HTTP_ORIGIN']) ? $_SERVER['HTTP_ORIGIN'] : (!empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '');
		$originDomain = AIOverviewController::registrableDomain($originHeader);
		$registeredDomain = AIOverviewController::registrableDomain($siteInfo['domain']);
		if ($originHeader === '' || $originDomain === '' || $originDomain !== $registeredDomain) {
			exit;
		}

		if (!empty($_SERVER['HTTP_ORIGIN'])) {
			header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);
			header('Vary: Origin');
		}

		$tokenCap = defined('AIV_RATE_LIMIT_PER_TOKEN') ? intval(AIV_RATE_LIMIT_PER_TOKEN) : 120;
		if (!$this->__checkRateLimit('token:' . $token, $tokenCap)) {
			exit;
		}
		$remoteIp = !empty($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '';
		if ($remoteIp !== '') {
			$ipCap = defined('AIV_RATE_LIMIT_PER_IP') ? intval(AIV_RATE_LIMIT_PER_IP) : 60;
			if (!$this->__checkRateLimit('ip:' . $remoteIp, $ipCap)) {
				exit;
			}
		}

		// is_referral_source, not just is_active - every field in this payload
		// is untrusted, so the server enforces the same "is this hostname
		// actually a click source" rule the snippet applies client-side,
		// rather than trusting the caller not to pass a bot-only vendor
		// domain (e.g. google.com) directly.
		$platformInfo = $this->dbHelper->getRow('ai_platforms', "hostname='" . addslashes($platform) . "' and is_active=1 and is_referral_source=1");
		if (empty($platformInfo)) {
			exit;
		}

		// re-derive the path server-side - defense in depth, every field is untrusted
		$urlPath = strtok($urlPath, '?');
		$urlPath = strtok($urlPath, '#');
		if (empty($urlPath)) $urlPath = '/';
		$urlPath = mb_substr($urlPath, 0, 2048);

		$websiteId = intval($siteInfo['website_id']);
		$hitDate = date('Y-m-d');
		$urlHashHex = bin2hex(md5($urlPath, true));
		$platformCode = addslashes($platformInfo['platform']);
		$urlPathSql = addslashes($urlPath);

		// checked before the aggregate-on-write insert below, so "first
		// hit" reflects state prior to this request
		$this->__alertOnFirstPlatformHit($websiteId, $platformInfo['platform'], 'ai_referrals', $platformInfo['display_name']);

		$sql = "INSERT INTO ai_referrals (website_id, hit_date, platform, url_path, url_hash, hits, created_at, updated_at)
				VALUES ($websiteId, '$hitDate', '$platformCode', '$urlPathSql', UNHEX('$urlHashHex'), 1, NOW(), NOW())
				ON DUPLICATE KEY UPDATE hits = hits + 1, updated_at = NOW()";
		$this->db->query($sql);

		$this->db->query("UPDATE ai_visibility_sites SET last_seen_at=NOW() WHERE id=" . intval($siteInfo['id']));

		exit;
	}

	/**
	 * Public bot-hit ingest - called only from aibot-collect.php. This is a
	 * server-to-server POST from the customer's own hosting server (sent by
	 * the collector script), never a browser, so there is no Origin/Referer
	 * to validate and no CORS handling applies. The 'verified' flag is
	 * trusted as reported by the collector - FCrDNS runs there, at the only
	 * point where the real crawler IP is known with certainty (see
	 * generateBotCollectorScript()). Always responds fast with no body.
	 */
	function ingestBotHit() {
		header('Content-Type: text/plain');
		http_response_code(204);

		$maxBytes = 4096;
		$contentLength = isset($_SERVER['CONTENT_LENGTH']) ? intval($_SERVER['CONTENT_LENGTH']) : 0;
		if ($contentLength > $maxBytes) {
			exit;
		}

		$rawBody = file_get_contents('php://input', false, null, 0, $maxBytes + 1);
		if (empty($rawBody) || strlen($rawBody) > $maxBytes) {
			exit;
		}

		$payload = json_decode($rawBody, true);
		if (empty($payload) || !is_array($payload)) {
			exit;
		}

		$token = isset($payload['t']) ? trim((string)$payload['t']) : '';
		$userAgent = isset($payload['ua']) ? (string)$payload['ua'] : '';
		$verified = !empty($payload['verified']) ? 1 : 0;
		$urlPath = isset($payload['u']) ? (string)$payload['u'] : '';

		if ($token === '' || strlen($token) > 64 || $userAgent === '') {
			exit;
		}

		$siteInfo = $this->dbHelper->getRow('ai_visibility_sites', "token='" . addslashes($token) . "'");
		if (empty($siteInfo)) {
			exit;
		}

		$tokenCap = defined('AIV_RATE_LIMIT_PER_TOKEN') ? intval(AIV_RATE_LIMIT_PER_TOKEN) : 120;
		if (!$this->__checkRateLimit('bot-token:' . $token, $tokenCap)) {
			exit;
		}

		// classify by matching the reported UA against known crawler
		// patterns - unmatched UAs (the prefilter is deliberately broad,
		// so plenty won't match anything here) are silently dropped
		$matched = $this->__matchBotPlatform($userAgent);
		if (empty($matched)) {
			exit;
		}

		// re-derive the path server-side - defense in depth, every field is untrusted
		$urlPath = strtok($urlPath, '?');
		$urlPath = strtok($urlPath, '#');
		if (empty($urlPath)) $urlPath = '/';
		$urlPath = mb_substr($urlPath, 0, 2048);

		$websiteId = intval($siteInfo['website_id']);
		$this->__recordBotHit($websiteId, $matched['platform'], $matched['display_name'], $verified, $urlPath);

		exit;
	}

	// func to match a User-Agent string against the ai_platforms bot_ua_pattern
	// catalog - shared by the live HTTP ingest path (ingestBotHit(), above)
	// and the access-log-based path (__tailAccessLogForWebsite()). Returns
	// ['platform', 'display_name'] on the first match, or null.
	function __matchBotPlatform($userAgent) {
		$platformList = $this->db->select("SELECT platform, display_name, bot_ua_pattern FROM ai_platforms WHERE is_active=1 AND bot_ua_pattern IS NOT NULL AND bot_ua_pattern != ''");
		foreach ($platformList as $platformRow) {
			if (stripos($userAgent, $platformRow['bot_ua_pattern']) !== false) {
				return ['platform' => $platformRow['platform'], 'display_name' => $platformRow['display_name']];
			}
		}
		return null;
	}

	/**
	 * Records one AI bot hit against ai_bot_hits (aggregate-on-write) and
	 * fires the first-hit alert - shared by the live HTTP ingest path
	 * (ingestBotHit()) and the access-log-based path
	 * (__tailAccessLogForWebsite()). Unlike ingestBotHit(), the log-based
	 * caller never has a token-derived ai_visibility_sites row on hand, so
	 * the last-seen update below is keyed on website_id (a UNIQUE key on
	 * that table) rather than a pre-fetched site id.
	 */
	function __recordBotHit($websiteId, $platform, $displayName, $verified, $urlPath) {
		$websiteId = intval($websiteId);
		$verified = !empty($verified) ? 1 : 0;
		$hitDate = date('Y-m-d');
		$urlHashHex = bin2hex(md5($urlPath, true));
		$platformSql = addslashes($platform);
		$urlPathSql = addslashes($urlPath);

		// checked before the aggregate-on-write insert below, so "first
		// hit" reflects state prior to this request
		$this->__alertOnFirstPlatformHit($websiteId, $platform, 'ai_bot_hits', $displayName);

		$sql = "INSERT INTO ai_bot_hits (website_id, hit_date, platform, verified, url_path, url_hash, hits, created_at, updated_at)
				VALUES ($websiteId, '$hitDate', '$platformSql', $verified, '$urlPathSql', UNHEX('$urlHashHex'), 1, NOW(), NOW())
				ON DUPLICATE KEY UPDATE hits = hits + 1, updated_at = NOW()";
		$this->db->query($sql);

		$this->db->query("UPDATE ai_visibility_sites SET bot_last_seen_at=NOW() WHERE website_id=$websiteId");
	}

	/**
	 * On-premise AI bot detection via the tracked website's own real access
	 * log - for co-located sites only (see ai_visibility_site_access,
	 * admin-configured). Catches everything (no JS/snippet dependency, no
	 * false negatives from ad blockers/CSP) and runs FCrDNS verification
	 * safely here in a batched background cron job instead of blocking a
	 * real visitor's page load the way the downloadable collector script
	 * must. Called unconditionally from cron.php's tail, same spot as the
	 * existing pruneOldReferrals()/pruneOldBotHits() calls - opportunistic
	 * and config-driven, not a first-class seotool needing routeCronJob().
	 */
	function processAccessLogsForBotHits() {
		// never-run sites first, so one high-volume site can't starve every
		// other configured site's turn under the shared byte budget below
		$sites = $this->db->select("SELECT * FROM ai_visibility_site_access WHERE access_log_path IS NOT NULL AND access_log_path != '' ORDER BY log_last_run_at IS NULL DESC, log_last_run_at ASC");
		if (empty($sites)) {
			return;
		}

		$byteBudget = defined('AIB_LOG_BYTES_PER_CRON_RUN') ? intval(AIB_LOG_BYTES_PER_CRON_RUN) : 5242880;
		$bytesUsed = 0;

		foreach ($sites as $siteAccess) {
			if ($bytesUsed >= $byteBudget) break;
			$bytesUsed += $this->__tailAccessLogForWebsite($siteAccess, $byteBudget - $bytesUsed);
		}
	}

	/**
	 * Tails one website's access log from its persisted offset, parsing
	 * Combined Log Format lines and recording AI bot hits. Returns bytes
	 * actually read (so the caller can track the shared per-run budget).
	 *
	 * Rotation/truncation handling is v1-scoped: the CURRENT active log
	 * file only, no gzip/rotated-file chasing. If the file's inode changed
	 * (rotation) or its size shrank below the stored offset (truncation),
	 * the offset resets to 0 - any lines written between the last
	 * successful run and the rotation are lost outright, not merely
	 * delayed. Accepted tradeoff for v1 simplicity/no shell-out.
	 */
	function __tailAccessLogForWebsite($siteAccess, $byteBudget) {
		$websiteId = intval($siteAccess['website_id']);
		$pathStatus = $this->__validateAccessLogPath($siteAccess['access_log_path']);
		if (empty($pathStatus['readable'])) {
			// path deleted/permissions changed since admin configured it -
			// skip gracefully, nothing to charge against the byte budget
			return 0;
		}

		$path = $pathStatus['real'];
		$stat = @stat($path);
		if (empty($stat)) {
			return 0;
		}

		$currentInode = $stat['ino'];
		$currentSize = $stat['size'];
		$storedInode = $siteAccess['log_inode'];
		$offset = intval($siteAccess['log_offset']);

		if (($storedInode !== null && intval($storedInode) !== $currentInode) || $currentSize < $offset) {
			$offset = 0;
		}

		if ($offset >= $currentSize) {
			// nothing new to read - still record that we checked
			$this->dbHelper->updateRow('ai_visibility_site_access', [
				'log_inode|int' => $currentInode,
				'log_last_run_at' => 'NOW()',
			], "website_id=$websiteId");
			return 0;
		}

		$fh = @fopen($path, 'r');
		if ($fh === false) {
			return 0;
		}

		fseek($fh, $offset);
		$readLimit = min($byteBudget, $currentSize - $offset);
		$chunk = $readLimit > 0 ? fread($fh, $readLimit) : '';
		fclose($fh);

		$bytesRead = strlen($chunk);
		if ($bytesRead === 0) {
			return 0;
		}

		// only advance the offset to the last COMPLETE line - a trailing
		// partial line is safely re-read next run, never causes duplicate
		// processing
		$lastNewline = strrpos($chunk, "\n");
		if ($lastNewline === false) {
			// no complete line in this chunk at all - nothing to process
			// or advance past yet
			return $bytesRead;
		}
		$completeChunk = substr($chunk, 0, $lastNewline);
		$newOffset = $offset + $lastNewline + 1;

		$ipCache = []; // per-run FCrDNS dedupe
		$ipVerifyCap = defined('AIB_LOG_MAX_IPS_PER_CRON_RUN') ? intval(AIB_LOG_MAX_IPS_PER_CRON_RUN) : 500;

		foreach (explode("\n", $completeChunk) as $line) {
			if ($line === '') continue;

			$parsed = $this->__parseCombinedLogLine($line);
			if (empty($parsed)) continue; // unparseable line - skip, not fatal

			$matched = $this->__matchBotPlatform($parsed['user_agent']);
			if (empty($matched)) continue;

			$ip = $parsed['ip'];
			if (!array_key_exists($ip, $ipCache)) {
				if (count($ipCache) < $ipVerifyCap) {
					$ipCache[$ip] = $this->__verifyFcrdns($ip);
				} else {
					// verification capacity exhausted this run - still
					// record the hit, just unverified, never drop it
					$ipCache[$ip] = false;
				}
			}

			$urlPath = strtok($parsed['path'], '?');
			$urlPath = strtok($urlPath, '#');
			if (empty($urlPath)) $urlPath = '/';
			$urlPath = mb_substr($urlPath, 0, 2048);

			$this->__recordBotHit($websiteId, $matched['platform'], $matched['display_name'], $ipCache[$ip], $urlPath);
		}

		$this->dbHelper->updateRow('ai_visibility_site_access', [
			'log_offset|int' => $newOffset,
			'log_inode|int' => $currentInode,
			'log_last_run_at' => 'NOW()',
		], "website_id=$websiteId");

		return $bytesRead;
	}

	// func to parse one Apache/Nginx Combined Log Format line - unparseable
	// lines (custom nginx log_format configs, etc.) return null and are
	// skipped by the caller, never fatal
	function __parseCombinedLogLine($line) {
		if (!preg_match('/^(\S+) \S+ \S+ \[[^\]]+\] "(\S+) (\S+)[^"]*" \d+ \d+ "[^"]*" "([^"]*)"/', $line, $m)) {
			return null;
		}
		return ['ip' => $m[1], 'method' => $m[2], 'path' => $m[3], 'user_agent' => $m[4]];
	}

	/**
	 * Native FCrDNS (Forward-Confirmed reverse DNS) check: reverse-DNS the
	 * IP, then forward-confirm it resolves back to the same IP - the same
	 * method used to verify Googlebot. This mirrors the algorithm generated
	 * as a heredoc STRING inside generateBotCollectorScript() for a third
	 * party's server (deliberately dependency-free there, "no remote
	 * includes") - it is a parallel implementation, not shared code, since
	 * that heredoc must stand alone on someone else's server. Run here,
	 * safely, in a batched background cron job rather than blocking a real
	 * visitor's page load.
	 */
	function __verifyFcrdns($ip) {
		if (empty($ip)) return false;

		$prevTimeout = ini_get('default_socket_timeout');
		ini_set('default_socket_timeout', 2);
		try {
			$host = @gethostbyaddr($ip);
			if (!$host || $host === $ip) {
				return false;
			}
			return @gethostbyname($host) === $ip;
		} finally {
			ini_set('default_socket_timeout', $prevTimeout);
		}
	}

	# func to check+increment a fixed 60s-window rate-limit bucket, returns false when over cap
	function __checkRateLimit($bucketKeyBase, $capPerMinute) {
		$windowStart = intval(floor(time() / 60));
		$bucketKey = addslashes(substr($bucketKeyBase, 0, 100));

		$this->db->query("INSERT INTO ai_visibility_rate_limit (bucket_key, window_start, hit_count)
				VALUES ('$bucketKey', $windowStart, 1)
				ON DUPLICATE KEY UPDATE hit_count = hit_count + 1");

		$row = $this->dbHelper->getRow('ai_visibility_rate_limit', "bucket_key='$bucketKey' and window_start=$windowStart");
		return !empty($row) && intval($row['hit_count']) <= $capPerMinute;
	}

	/**
	 * Alerts the website owner the first time a website is ever seen
	 * receiving a hit from a given platform, in either ai_referrals
	 * (click referrals) or ai_bot_hits (crawler visits). Must be called
	 * BEFORE the aggregate-on-write INSERT ... ON DUPLICATE KEY UPDATE for
	 * that hit, since the existence check below is what distinguishes
	 * "first ever" from "one more of many" - once the row exists this
	 * always no-ops. createAlert() itself dedupes same subject+message
	 * per user per day, so this is safe to call on every ingest.
	 */
	function __alertOnFirstPlatformHit($websiteId, $platform, $table, $displayName) {
		$exists = $this->dbHelper->getRow($table, "website_id=" . intval($websiteId) . " and platform='" . addslashes($platform) . "'");
		if (!empty($exists)) {
			return;
		}

		$websiteInfo = $this->dbHelper->getRow('websites', "id=" . intval($websiteId));
		if (empty($websiteInfo['user_id'])) {
			return;
		}

		include_once(SP_CTRLPATH . "/alerts.ctrl.php");
		$alertCtrl = new AlertController();
		$alertCtrl->createAlert([
			'alert_subject' => 'New AI Visibility Platform Detected',
			'alert_message' => ($websiteInfo['url'] ?? 'Your website') . " just received its first tracked " . ($table == 'ai_bot_hits' ? 'crawl' : 'referral') . " from " . $displayName . ".",
			'alert_category' => 'reports',
			'alert_url' => SP_WEBPATH . "/aivisibility.php?website_id=" . intval($websiteId) . "&sec=" . ($table == 'ai_bot_hits' ? 'botreport' : 'report'),
		], $websiteInfo['user_id']);
	}

	/**
	 * Weekly AI Visibility digest email: opt-out, sent at most once per 7
	 * days per user (reports_settings.ai_visibility_last_digest_sent) -
	 * deliberately independent of the main report scheduler's
	 * user-configurable interval, mirroring CronController::
	 * refreshAllAIInsights()'s email digest pattern rather than that one.
	 * Skipped entirely for a user whose websites had zero AI referral/bot-
	 * crawl traffic and no AI Overview presence all week (no point
	 * emailing all-zeros) - but the attempt is still recorded so a quiet
	 * week doesn't get recomputed on every subsequent cron run. Called
	 * unconditionally from cron.php; one user's email failing must not
	 * affect the rest.
	 */
	function sendWeeklyDigests() {
		if (!defined('SP_AI_VISIBILITY_EMAIL_NOTIFICATION') || !SP_AI_VISIBILITY_EMAIL_NOTIFICATION) {
			return;
		}

		include_once(SP_CTRLPATH . "/report.ctrl.php");
		include_once(SP_CTRLPATH . "/user.ctrl.php");
		$reportCtrler = new ReportController();
		$userCtrler = new UserController();

		$websiteList = $this->db->select("SELECT id, name, user_id FROM websites WHERE status=1");
		$websitesByUser = [];
		foreach ($websiteList as $w) {
			$websitesByUser[$w['user_id']][] = $w;
		}

		foreach ($websitesByUser as $userId => $userWebsites) {
			$repSetInfo = $reportCtrler->getUserReportSettings($userId);
			if (empty($repSetInfo['ai_visibility_email_notification'])) {
				continue;
			}

			$lastSent = $repSetInfo['ai_visibility_last_digest_sent'] ?? null;
			if (!empty($lastSent) && strtotime($lastSent) > strtotime('-7 days')) {
				continue; // already sent (or attempted) within the last 7 days
			}

			$summaryByWebsite = [];
			$hasAnyTraffic = false;
			foreach ($userWebsites as $w) {
				$summary = $this->__getWeeklyDigestSummaryForWebsite($w['id']);
				if ($summary['referrals'] > 0 || $summary['bot_hits'] > 0 || !empty($summary['aio']['present'])) {
					$hasAnyTraffic = true;
				}
				$summaryByWebsite[$w['id']] = array_merge(['name' => $w['name']], $summary);
			}

			$reportCtrler->updateUserReportSetting($userId, 'ai_visibility_last_digest_sent', date('Y-m-d'));

			if (!$hasAnyTraffic) {
				continue;
			}

			$userInfo = $userCtrler->__getUserInfo($userId);
			if (empty($userInfo['email'])) {
				continue;
			}

			try {
				$this->sendWeeklyDigestEmail($userInfo, $summaryByWebsite);
			} catch (Throwable $e) {
				continue;
			}
		}
	}

	// func to compute one website's last-7-days AI Visibility digest
	// numbers - same underlying data/helpers as the Overview dashboard,
	// just a 7-day window instead of 30
	function __getWeeklyDigestSummaryForWebsite($websiteId) {
		$websiteId = intval($websiteId);
		$fromDate = date('Y-m-d', strtotime('-7 days'));

		$referrals = intval($this->db->select("SELECT COALESCE(SUM(hits),0) AS total FROM ai_referrals WHERE website_id=$websiteId AND hit_date >= '$fromDate'", true)['total']);
		$botHits = intval($this->db->select("SELECT COALESCE(SUM(hits),0) AS total FROM ai_bot_hits WHERE website_id=$websiteId AND hit_date >= '$fromDate'", true)['total']);
		$aio = $this->__getAioSummaryForWebsite($websiteId);

		return ['referrals' => $referrals, 'bot_hits' => $botHits, 'aio' => $aio];
	}

	function sendWeeklyDigestEmail($userInfo, $summaryByWebsite) {
		include_once(SP_CTRLPATH . "/user.ctrl.php");

		$aivTexts = $this->getLanguageTexts('aivisibility', $userInfo['lang_code']);
		$this->set('aivTexts', $aivTexts);
		$this->set('commonTexts', $this->getLanguageTexts('common', $userInfo['lang_code']));
		$this->set('loginTexts', $this->getLanguageTexts('login', $userInfo['lang_code']));

		$name = trim($userInfo['first_name'] . ' ' . $userInfo['last_name']);
		$this->set('name', $name);
		$this->set('summaryByWebsite', $summaryByWebsite);

		$subject = !empty($aivTexts['ai_visibility_email_subject']) ? $aivTexts['ai_visibility_email_subject'] : 'Your AI Visibility summary this week';
		$content = $this->getViewContent('email/aivisibilitydigest');

		$userController = new UserController();
		$adminInfo = $userController->__getAdminInfo();
		$adminName = $adminInfo['first_name'] . "-" . $adminInfo['last_name'];
		$this->set('adminName', $adminName);

		return sendMail($adminInfo['email'], $adminName, $userInfo['email'], $subject, $content);
	}

}
?>
